### ISSUE TITLE
Background image for checklist

### ISSUE THREAD

**Issue by zly-wik** [zly-wik/shopping-list#10]
- [x] Project setup for working with media files
- [x] Image field in Checklist model
- [x] Serializer

**Comment by zly-wik** [comment]
- [ ] Limit image size to 500kb
