### ISSUE TITLE
Write tests for UserProfile & Checklist and Item CRUD

### ISSUE THREAD

**Issue by zly-wik** [zly-wik/shopping-list#5]
- [x] CRUD for Checklist
- [x] CRUD for Item
- [x] Retrieve for UserProfile `/me` endpoint

**Comment by zly-wik** [comment]
### Pytest setup for work within docker-compose

**Comment by zly-wik** [comment]
### Checklist tests:
- [ ] Create
- [ ] Retrieve
- [ ] Update
- [ ] Delete

**Comment by zly-wik** [comment]
### Important:
 - Create separate (SQLite3) Database for tests as GitHub actions has no access to PostrgreSQL db inside docker-compose

**Comment by zly-wik** [comment]
### Item tests:
- [ ] Create
- [ ] Retrieve
- [ ] Update
- [ ] Delete
